In [1]:
import pandas as pd

In [2]:
df= pd.read_csv(r"C:\Users\anupr\OneDrive\Desktop\laptop_price_prediction\laptop_price.csv",encoding='latin-1')

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\anupr\\OneDrive\\Desktop\\laptop_price_prediction\\laptop_price.csv'

In [ ]:
df

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1316,Lenovo,Yoga 500-14ISK,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,638.00
1299,1317,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,1499.00
1300,1318,Lenovo,IdeaPad 100S-14IBR,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,229.00
1301,1319,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.00
1302,1320,Asus,X553SA-XX031T (N3050/4GB/500GB/W10),Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,369.00

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

laptop_ID           0
Company             0
Product             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price_euros         0
dtype: int64

In [3]:
df.drop(["laptop_ID","Product",	"TypeName",	"Weight"], axis =1, inplace=True)

NameError: name 'df' is not defined

In [4]:
df

NameError: name 'df' is not defined

In [5]:
df.Company.unique()

NameError: name 'df' is not defined

In [6]:
co_d={    'Apple':0,        'HP':1,      'Acer':2,      'Asus':3,      'Dell':4,    'Lenovo':5,
     'Chuwi':6,       'MSI':7, 'Microsoft':8,   'Toshiba':9,    'Huawei':10,    'Xiaomi':11,
      'Vero':12,     'Razer':13,  'Mediacom':14,   'Samsung':15,    'Google':16,   'Fujitsu':17,
        'LG':18}
df["Company"]=df["Company"].map(co_d)

NameError: name 'df' is not defined

In [7]:
df

NameError: name 'df' is not defined

In [8]:
Ram_d={ "2GB":2, "4GB":4, "6GB":6, "8GB":8, "12GB":12, "16GB":16, "24GB":24, "32GB":32, "64GB":64}
df["Ram"]=df["Ram"].map(Ram_d)

NameError: name 'df' is not defined

In [105]:
OpSys_d= {"macOS":0, "No OS":1, "Windows 10":2, "Mac OS X":3, "Linux":4, "Android":5, "Windows 10 S":6, "Chrome OS":7, "Windows 7":8} 
df["OpSys"]=df["OpSys"].map(OpSys_d)

In [106]:
df.ScreenResolution.unique()

<StringArray>
[           'IPS Panel Retina Display 2560x1600',
                                      '1440x900',
                             'Full HD 1920x1080',
            'IPS Panel Retina Display 2880x1800',
                                      '1366x768',
                   'IPS Panel Full HD 1920x1080',
            'IPS Panel Retina Display 2304x1440',
     'IPS Panel Full HD / Touchscreen 1920x1080',
               'Full HD / Touchscreen 1920x1080',
              'Touchscreen / Quad HD+ 3200x1800',
               'IPS Panel Touchscreen 1920x1200',
                         'Touchscreen 2256x1504',
              'Quad HD+ / Touchscreen 3200x1800',
                            'IPS Panel 1366x768',
 'IPS Panel 4K Ultra HD / Touchscreen 3840x2160',
                   'IPS Panel Full HD 2160x1440',
           '4K Ultra HD / Touchscreen 3840x2160',
                         'Touchscreen 2560x1440',
                                      '1600x900',
               'IPS Panel 4K Ultra HD 3840x2160',
                         '4K Ultra HD 3840x2160',
                          'Touchscreen 1366x768',
                    'IPS Panel Full HD 1366x768',
                           'IPS Panel 2560x1440',
                   'IPS Panel Full HD 2560x1440',
            'IPS Panel Retina Display 2736x1824',
                         'Touchscreen 2400x1600',
                                     '2560x1440',
                  'IPS Panel Quad HD+ 2560x1440',
                  'IPS Panel Quad HD+ 3200x1800',
    'IPS Panel Quad HD+ / Touchscreen 3200x1800',
                'IPS Panel Touchscreen 1366x768',
                                     '1920x1080',
                   'IPS Panel Full HD 1920x1200',
 'IPS Panel Touchscreen / 4K Ultra HD 3840x2160',
               'IPS Panel Touchscreen 2560x1440',
               'Touchscreen / Full HD 1920x1080',
                            'Quad HD+ 3200x1800',
           'Touchscreen / 4K Ultra HD 3840x2160',
               'IPS Panel Touchscreen 2400x1600']
Length: 40, dtype: str

In [107]:
SR_d= {
        "IPS Panel Retina Display 2560x1600":0, "1440x900":1, "Full HD 1920x1080":2, 
        "IPS Panel Retina Display 2880x1800":3, "1366x768":4, "IPS Panel Full HD 1920x1080":5, 
        "IPS Panel Full HD / Touchscreen 1920x1080":6, "Full HD / Touchscreen 1920x1080":7, 
        "Touchscreen / Quad HD+ 3200x1800":8, "IPS Panel Touchscreen 1920x1200":9, 
        "Touchscreen 2256x1504": 10, "Quad HD+ / Touchscreen 3200x1800":11, 
        "Touchscreen 2560x1440":12, "IPS Panel 4K Ultra HD / Touchscreen 3840x2160":13, 
        "4K Ultra HD / Touchscreen 3840x2160":14, "IPS Panel 4K Ultra HD 3840x2160":15, 
        "IPS Panel Full HD 2160x1440":16, "IPS Panel Retina Display 2304x1440":17, 
        "IPS Panel Retina Display 2736x1824":18, "1600x900":19, "IPS Panel 1366x768":20, 
        "Touchscreen 1366x768":21, "IPS Panel Full HD 1366x768":22, "2560x1440":23, 
        "IPS Panel Quad HD+ 2560x1440":24, "Touchscreen 2400x1600":25, 
        "IPS Panel Touchscreen 2400x1600":26, "Quad HD+ 3200x1800":27, "1920x1080":28, "IPS Panel Quad HD+ / Touchscreen 3200x1800":29
}
df["ScreenResolution"]=df["ScreenResolution"].map(SR_d)

In [108]:
df

,Company,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Price_euros
0,0,13.3,0.0,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,0,1339.69
1,0,13.3,1.0,Intel Core i5 1.8GHz,8,128GB Flash Storage,Intel HD Graphics 6000,0,898.94
2,1,15.6,2.0,Intel Core i5 7200U 2.5GHz,8,256GB SSD,Intel HD Graphics 620,1,575.00
3,0,15.4,3.0,Intel Core i7 2.7GHz,16,512GB SSD,AMD Radeon Pro 455,0,2537.45
4,0,13.3,0.0,Intel Core i5 3.1GHz,8,256GB SSD,Intel Iris Plus Graphics 650,0,1803.60
...,...,...,...,...,...,...,...,...,...
1298,5,14.0,6.0,Intel Core i7 6500U 2.5GHz,4,128GB SSD,Intel HD Graphics 520,2,638.00
1299,5,13.3,29.0,Intel Core i7 6500U 2.5GHz,16,512GB SSD,Intel HD Graphics 520,2,1499.00
1300,5,14.0,4.0,Intel Celeron Dual Core N3050 1.6GHz,2,64GB Flash Storage,Intel HD Graphics,2,229.00
1301,1,15.6,4.0,Intel Core i7 6500U 2.5GHz,6,1TB HDD,AMD Radeon R5 M330,2,764.00
1302,3,15.6,4.0,Intel Celeron Dual Core N3050 1.6GHz,4,500GB HDD,Intel HD Graphics,2,369.00

In [109]:
cpu_list = {
    "AMD A10-Series 9600P 2.4GHz",
    "AMD A10-Series 9620P 2.5GHz",
    "AMD A10-Series A10-9620P 2.5GHz",
    "AMD A12-Series 9700P 2.5GHz",
    "AMD A12-Series 9720P 2.7GHz",
    "AMD A12-Series 9720P 3.6GHz",
    "AMD A4-Series 7210 2.2GHz",
    "AMD A6-Series 7310 2GHz",
    "AMD A6-Series 9220 2.5GHz",
    "AMD A6-Series A6-9220 2.5GHz",
    "AMD A8-Series 7410 2.2GHz",
    "AMD A9-Series 9410 2.9GHz",
    "AMD A9-Series 9420 3GHz",
    "AMD A9-Series A9-9420 3GHz",
    "AMD E-Series 6110 1.5GHz",
    "AMD E-Series 7110 1.8GHz",
    "AMD E-Series 9000 2.2GHz",
    "AMD E-Series 9000e 1.5GHz",
    "AMD E-Series E2-6110 1.5GHz",
    "AMD E-Series E2-9000e 1.5GHz",
    "AMD FX 8800P 2.1GHz",
    "AMD FX 9830P 3GHz",
    "AMD Ryzen 1600 3.2GHz",
    "AMD Ryzen 1700 3GHz",
    "Intel Atom X5-Z8350 1.44GHz",
    "Intel Atom Z8350 1.92GHz",
    "Intel Atom x5-Z8300 1.44GHz",
    "Intel Atom x5-Z8350 1.44GHz",
    "Intel Atom x5-Z8550 1.44GHz",
    "Intel Celeron Dual Core 3205U 1.5GHz",
    "Intel Celeron Dual Core 3855U 1.6GHz",
    "Intel Celeron Dual Core N3050 1.6GHz",
    "Intel Celeron Dual Core N3060 1.6GHz",
    "Intel Celeron Dual Core N3350 1.1GHz",
    "Intel Celeron Quad Core N3160 1.6GHz",
    "Intel Celeron Quad Core N3450 1.1GHz",
    "Intel Core M 1.1GHz",
    "Intel Core M 1.2GHz",
    "Intel Core M 6Y54 1.1GHz",
    "Intel Core M 6Y75 1.2GHz",
    "Intel Core M 7Y30 1.0GHz",
    "Intel Core M M3-6Y30 0.9GHz",
    "Intel Core M M7-6Y75 1.2GHz",
    "Intel Core M m3 1.2GHz",
    "Intel Core M m3-7Y30 2.2GHz",
    "Intel Core M m7-6Y75 1.2GHz",
    "Intel Core i3 6006U 2.0GHz",
    "Intel Core i3 6006U 2.2GHz",
    "Intel Core i3 6006U 2GHz",
    "Intel Core i3 6100U 2.1GHz",
    "Intel Core i3 6100U 2.3GHz",
    "Intel Core i3 7100U 2.4GHz",
    "Intel Core i3 7130U 2.7GHz",
    "Intel Core i5 1.3GHz",
    "Intel Core i5 1.6GHz",
    "Intel Core i5 1.8GHz",
    "Intel Core i5 2.3GHz",
    "Intel Core i5 3.1GHz",
    "Intel Core i5 6200U 2.3GHz",
    "Intel Core i5 6300HQ 2.3GHz",
    "Intel Core i5 6300U 2.4GHz",
    "Intel Core i5 6440HQ 2.6GHz",
    "Intel Core i5 7200U 2.5GHz",
    "Intel Core i5 7200U 2.7GHz",
    "Intel Core i5 7300HQ 2.5GHz",
    "Intel Core i5 7300U 2.6GHz",
    "Intel Core i5 7440HQ 2.8GHz",
    "Intel Core i5 7500U 2.7GHz",
    "Intel Core i5 7Y54 1.2GHz",
    "Intel Core i5 7Y57 1.2GHz",
    "Intel Core i5 8250U 1.6GHz",
    "Intel Core i7 2.2GHz",
    "Intel Core i7 2.7GHz",
    "Intel Core i7 2.8GHz",
    "Intel Core i7 2.9GHz",
    "Intel Core i7 6500U 2.5GHz",
    "Intel Core i7 6560U 2.2GHz",
    "Intel Core i7 6600U 2.6GHz",
    "Intel Core i7 6700HQ 2.6GHz",
    "Intel Core i7 6820HK 2.7GHz",
    "Intel Core i7 6820HQ 2.7GHz",
    "Intel Core i7 6920HQ 2.9GHz",
    "Intel Core i7 7500U 2.7GHz",
    "Intel Core i7 7560U 2.4GHz",
    "Intel Core i7 7660U 2.5GHz",
    "Intel Core i7 7700HQ 2.8GHz",
    "Intel Core i7 7820HK 2.9GHz",
    "Intel Core i7 7820HQ 2.9GHz",
    "Intel Core i7 7Y75 1.3GHz",
    "Intel Core i7 8550U 1.8GHz",
    "Intel Core i7 8650U 1.9GHz",
    "Intel Pentium Dual Core 4405U 2.1GHz",
    "Intel Pentium Dual Core 4405Y 1.5GHz",
    "Intel Pentium Dual Core N4200 1.1GHz",
    "Intel Pentium Quad Core N3700 1.6GHz",
    "Intel Pentium Quad Core N3710 1.6GHz",
    "Intel Pentium Quad Core N4200 1.1GHz",
    "Intel Xeon E3-1505M V6 3GHz",
    "Intel Xeon E3-1535M v5 2.9GHz",
    "Intel Xeon E3-1535M v6 3.1GHz",
    "Samsung Cortex A72&A53 2.0GHz"
}
cpu_dict = {cpu: i for i, cpu in enumerate(cpu_list)}
df["Cpu"]=df["Cpu"].map(cpu_dict)

In [ ]:
gpu_list = [
    "AMD FirePro W4190M",
    "AMD FirePro W5130M",
    "AMD FirePro W6150M",
    "AMD R17M-M1-70",
    "AMD Radeon 520",
    "AMD Radeon 530",
    "AMD Radeon Pro 455",
    "AMD Radeon Pro 555",
    "AMD Radeon Pro 560",
    "AMD Radeon R2",
    "AMD Radeon R2 Graphics",
    "AMD Radeon R4",
    "AMD Radeon R4 Graphics",
    "AMD Radeon R5",
    "AMD Radeon R5 M315",
    "AMD Radeon R5 M330",
    "AMD Radeon R5 M420",
    "AMD Radeon R5 M420X",
    "AMD Radeon R5 M430",
    "AMD Radeon R7",
    "AMD Radeon R7 M360",
    "AMD Radeon R7 M440",
    "AMD Radeon R7 M445",
    "AMD Radeon RX 540",
    "AMD Radeon RX 550",
    "AMD Radeon RX 560",
    "AMD Radeon RX 580",
    "ARM Mali T860 MP4",
    "Intel HD Graphics",
    "Intel HD Graphics 400",
    "Intel HD Graphics 405",
    "Intel HD Graphics 500",
    "Intel HD Graphics 505",
    "Intel HD Graphics 510",
    "Intel HD Graphics 515",
    "Intel HD Graphics 520",
    "Intel HD Graphics 530",
    "Intel HD Graphics 5300",
    "Intel HD Graphics 6000",
    "Intel HD Graphics 615",
    "Intel HD Graphics 620",
    "Intel Iris Graphics 540",
    "Intel Iris Graphics 550",
    "Intel Iris Plus Graphics 640",
    "Intel Iris Plus Graphics 650",
    "Intel Iris Pro Graphics",
    "Intel UHD Graphics 620",
    "Nvidia GeForce 150MX",
    "Nvidia GeForce 920M",
    "Nvidia GeForce 920MX",
    "Nvidia GeForce 930M",
    "Nvidia GeForce 930MX",
    "Nvidia GeForce 940MX",
    "Nvidia GeForce GT 940MX",
    "Nvidia GeForce GTX 1050",
    "Nvidia GeForce GTX 1050 Ti",
    "Nvidia GeForce GTX 1050M",
    "Nvidia GeForce GTX 1060",
    "Nvidia GeForce GTX 1070",
    "Nvidia GeForce GTX 1070M",
    "Nvidia GeForce GTX 1080",
    "Nvidia GeForce GTX 940MX",
    "Nvidia GeForce GTX 950M",
    "Nvidia GeForce GTX 960M",
    "Nvidia GeForce GTX 965M",
    "Nvidia GeForce GTX 970M",
    "Nvidia GeForce GTX 980",
    "Nvidia GeForce GTX 980M",
    "Nvidia GeForce MX130",
    "Nvidia GeForce MX150",
    "Nvidia GTX 980 SLI",
    "Nvidia Quadro 3000M",
    "Nvidia Quadro M1000M",
    "Nvidia Quadro M1200",
    "Nvidia Quadro M2000M",
    "Nvidia Quadro M2200",
    "Nvidia Quadro M2200M",
    "Nvidia Quadro M3000M",
    "Nvidia Quadro M500M",
    "Nvidia Quadro M520M",
    "Nvidia Quadro M620",
    "Nvidia Quadro M620M"
]


gpu_dict = {gpu: i for i, gpu in enumerate(gpu_list)}
df["Gpu"]=df["Gpu"].map(gpu_dict)

In [111]:
df

,Company,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Price_euros
0,0,13.3,0.0,52.0,8,128GB SSD,43.0,0,1339.69
1,0,13.3,1.0,19.0,8,128GB Flash Storage,38.0,0,898.94
2,1,15.6,2.0,94.0,8,256GB SSD,40.0,1,575.00
3,0,15.4,3.0,49.0,16,512GB SSD,6.0,0,2537.45
4,0,13.3,0.0,34.0,8,256GB SSD,44.0,0,1803.60
...,...,...,...,...,...,...,...,...,...
1298,5,14.0,6.0,79.0,4,128GB SSD,35.0,2,638.00
1299,5,13.3,29.0,79.0,16,512GB SSD,35.0,2,1499.00
1300,5,14.0,4.0,27.0,2,64GB Flash Storage,28.0,2,229.00
1301,1,15.6,4.0,79.0,6,1TB HDD,15.0,2,764.00
1302,3,15.6,4.0,27.0,4,500GB HDD,28.0,2,369.00

In [116]:
memory_list = [
    "1.0TB HDD",
    "1.0TB Hybrid",
    "128GB Flash Storage",
    "128GB HDD",
    "128GB SSD",
    "128GB SSD + 1TB HDD",
    "128GB SSD + 2TB HDD",
    "16GB Flash Storage",
    "16GB SSD",
    "180GB SSD",
    "1TB HDD",
    "1TB SSD",
    "1TB SSD + 1TB HDD",
    "240GB SSD",
    "256GB Flash Storage",
    "256GB SSD",
    "256GB SSD + 1TB HDD",
    "256GB SSD + 256GB SSD",
    "256GB SSD + 2TB HDD",
    "256GB SSD + 500GB HDD",
    "2TB HDD",
    "32GB Flash Storage",
    "32GB HDD",
    "32GB SSD",
    "500GB HDD",
    "508GB Hybrid",
    "512GB Flash Storage",
    "512GB SSD",
    "512GB SSD + 1.0TB Hybrid",
    "512GB SSD + 1TB HDD",
    "512GB SSD + 2TB HDD",
    "512GB SSD + 512GB SSD",
    "64GB Flash Storage",
    "64GB Flash Storage + 1TB HDD",
    "64GB SSD",
    "8GB SSD"
]
memory_dict = {memory: i for i, memory in enumerate(memory_list)}
df["Memory"]=df["Memory"].map(memory_dict)

In [117]:
df

,Company,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Price_euros
0,0,13.3,0.0,52.0,8,4.0,43.0,0,1339.69
1,0,13.3,1.0,19.0,8,2.0,38.0,0,898.94
2,1,15.6,2.0,94.0,8,15.0,40.0,1,575.00
3,0,15.4,3.0,49.0,16,27.0,6.0,0,2537.45
4,0,13.3,0.0,34.0,8,15.0,44.0,0,1803.60
...,...,...,...,...,...,...,...,...,...
1298,5,14.0,6.0,79.0,4,4.0,35.0,2,638.00
1299,5,13.3,29.0,79.0,16,27.0,35.0,2,1499.00
1300,5,14.0,4.0,27.0,2,32.0,28.0,2,229.00
1301,1,15.6,4.0,79.0,6,10.0,15.0,2,764.00
1302,3,15.6,4.0,27.0,4,24.0,28.0,2,369.00

In [121]:
df.to_csv("CleanedData.csv")