In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

In [3]:
df=pd.read_csv(r"C:\Users\anupr\OneDrive\Desktop\laptop_price_prediction\Data\CleanedData.csv")

In [4]:
df

,Unnamed: 0,Company,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Price_euros
0,0,0,13.3,0.0,52.0,8,4.0,43.0,0,1339.69
1,1,0,13.3,1.0,19.0,8,2.0,38.0,0,898.94
2,2,1,15.6,2.0,94.0,8,15.0,40.0,1,575.00
3,3,0,15.4,3.0,49.0,16,27.0,6.0,0,2537.45
4,4,0,13.3,0.0,34.0,8,15.0,44.0,0,1803.60
...,...,...,...,...,...,...,...,...,...,...
1298,1298,5,14.0,6.0,79.0,4,4.0,35.0,2,638.00
1299,1299,5,13.3,29.0,79.0,16,27.0,35.0,2,1499.00
1300,1300,5,14.0,4.0,27.0,2,32.0,28.0,2,229.00
1301,1301,1,15.6,4.0,79.0,6,10.0,15.0,2,764.00
1302,1302,3,15.6,4.0,27.0,4,24.0,28.0,2,369.00

In [5]:
df.drop(['Unnamed: 0'], axis=1, inplace=True)

In [6]:
df

,Company,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Price_euros
0,0,13.3,0.0,52.0,8,4.0,43.0,0,1339.69
1,0,13.3,1.0,19.0,8,2.0,38.0,0,898.94
2,1,15.6,2.0,94.0,8,15.0,40.0,1,575.00
3,0,15.4,3.0,49.0,16,27.0,6.0,0,2537.45
4,0,13.3,0.0,34.0,8,15.0,44.0,0,1803.60
...,...,...,...,...,...,...,...,...,...
1298,5,14.0,6.0,79.0,4,4.0,35.0,2,638.00
1299,5,13.3,29.0,79.0,16,27.0,35.0,2,1499.00
1300,5,14.0,4.0,27.0,2,32.0,28.0,2,229.00
1301,1,15.6,4.0,79.0,6,10.0,15.0,2,764.00
1302,3,15.6,4.0,27.0,4,24.0,28.0,2,369.00