In [32]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor

In [2]:
df=pd.read_csv(r"C:\Users\anupr\OneDrive\Desktop\laptop_price_prediction\Data\CleanedData.csv")

In [3]:
df

,Unnamed: 0,Company,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Price_euros
0,0,0,13.3,0.0,91.0,8,4.0,43.0,0,1339.69
1,1,0,13.3,1.0,37.0,8,2.0,38.0,0,898.94
2,2,1,15.6,2.0,4.0,8,15.0,40.0,1,575.00
3,3,0,15.4,3.0,38.0,16,27.0,6.0,0,2537.45
4,4,0,13.3,0.0,18.0,8,15.0,44.0,0,1803.60
...,...,...,...,...,...,...,...,...,...,...
1298,1298,5,14.0,6.0,80.0,4,4.0,35.0,2,638.00
1299,1299,5,13.3,29.0,80.0,16,27.0,35.0,2,1499.00
1300,1300,5,14.0,4.0,86.0,2,32.0,28.0,2,229.00
1301,1301,1,15.6,4.0,80.0,6,10.0,15.0,2,764.00
1302,1302,3,15.6,4.0,86.0,4,24.0,28.0,2,369.00

In [4]:
df.drop(['Unnamed: 0'], axis=1, inplace=True)

In [5]:
df

,Company,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Price_euros
0,0,13.3,0.0,91.0,8,4.0,43.0,0,1339.69
1,0,13.3,1.0,37.0,8,2.0,38.0,0,898.94
2,1,15.6,2.0,4.0,8,15.0,40.0,1,575.00
3,0,15.4,3.0,38.0,16,27.0,6.0,0,2537.45
4,0,13.3,0.0,18.0,8,15.0,44.0,0,1803.60
...,...,...,...,...,...,...,...,...,...
1298,5,14.0,6.0,80.0,4,4.0,35.0,2,638.00
1299,5,13.3,29.0,80.0,16,27.0,35.0,2,1499.00
1300,5,14.0,4.0,86.0,2,32.0,28.0,2,229.00
1301,1,15.6,4.0,80.0,6,10.0,15.0,2,764.00
1302,3,15.6,4.0,86.0,4,24.0,28.0,2,369.00

In [6]:
y= df['Price_euros']

In [7]:
x= df.drop(["Price_euros"], axis=1)

In [8]:
x_train, x_test, y_train, y_test=train_test_split(x,y, test_size=0.2, random_state=42)

In [9]:
x_train.shape

(1042, 8)

In [10]:
y_train.shape

(1042,)

In [36]:
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression

# Create the imputer (strategy can be 'mean', 'median', or 'most_frequent')
imputer = SimpleImputer(strategy='median')

# Fit on training data and transform it
x_train_imputed = imputer.fit_transform(x_train)

# Don't forget to transform your test data later with the SAME imputer!
# 

# Now train your model

In [37]:
x_test_imputed = imputer.transform(x_test)

In [38]:
from sklearn.linear_model import LinearRegression

# 1. Initialize the correct model for continuous numbers
lr = LinearRegression()

# 2. Fit the model on your imputed data
lr.fit(x_train_imputed, y_train)

# 3. Now you can make continuous price predictions!
# predictions = lr.predict(x_test_imputed)

LinearRegression()

In [39]:
import joblib as jb
jb.dump(lr,"linear_regression.lb")

['linear_regression.lb']

In [40]:
lr.score(x_train_imputed,y_train)

0.6217549820011713

In [41]:
lr.score(x_test_imputed,y_test)

0.5899359137718698

In [42]:
sv =SVR()
sv.fit(x_train_imputed,y_train)

SVR()

In [43]:
import joblib as jb
jb.dump(sv,"support_vector.lb")

['support_vector.lb']

In [44]:
sv.score(x_train_imputed, y_train)

0.00013048271692850388

In [45]:
sv.score(x_test_imputed,y_test)

0.01246997120975768

In [46]:
dt=DecisionTreeRegressor()
dt.fit(x_train, y_train)

DecisionTreeRegressor()

In [47]:
jb.dump(dt, "decision_tree.lb")

['decision_tree.lb']

In [48]:
dt.score(x_train, y_train)

0.994511828976977

In [49]:
dt.score(x_test,y_test)

0.6219063568915997

In [50]:
rf= RandomForestRegressor()
rf.fit(x_train, y_train)

RandomForestRegressor()

In [51]:
import joblib as jb
jb.dump(rf, "Random_Forest.lb")

['Random_Forest.lb']

In [52]:
rf.score(x_train, y_train)

0.9687198411801581

In [53]:
rf.score(x_test, y_test)

0.7397111373762851